"""Paper storage against the real database, inside a transaction that is rolled back."""

from pathlib import Path

import pytest
from psycopg import AsyncConnection

from polymath.research.chunker import Chunk
from polymath.research.ingest import Outcome, ingest_pdf
from polymath.research.store import Paper, PaperStore

SHA_V1 = "a" * 64
SHA_V2 = "b" * 64
PAPER = Paper("liang2021yaw", "Yaw rate tracking-based path-following control", SHA_V1)
CHUNKS = [
    Chunk(("Introduction",), 1, 1, "Path following for autonomous vehicles is studied here."),
    Chunk(
        ("Results and discussions", "J-turn maneuver"),
        10,
        11,
        "Figure 8(f) shows the response of longitudinal velocity.",
    ),
]
LABELS = [str(n) for n in range(260, 273)]  # printed pages 260-272

PRIVATE = Path(__file__).parent / "fixtures" / "private"
LIANG_PDF = PRIVATE / (
    "Liang et al. - 2021 - Yaw rate tracking-based path-following control for four-wheel "
    "independent driving and four-wheel ind.pdf"
)


async def test_chunks_are_stored_with_section_pages_and_printed_label(
    paper_store: PaperStore, connection: AsyncConnection
) -> None:
    await paper_store.replace(PAPER, CHUNKS, LABELS)

    cur = await connection.execute(
        "SELECT ordinal, section, page_start, page_end, page_label FROM chunk ORDER BY ordinal"
    )
    assert await cur.fetchall() == [
        (0, ["Introduction"], 1, 1, "260"),
        (1, ["Results and discussions", "J-turn maneuver"], 10, 11, "269"),
    ]


async def test_an_unchanged_pdf_is_recognised(paper_store: PaperStore) -> None:
    await paper_store.replace(PAPER, CHUNKS, LABELS)

    assert await paper_store.is_current(PAPER.citekey, SHA_V1)
    assert not await paper_store.is_current(PAPER.citekey, SHA_V2)
    assert not await paper_store.is_current("someone2024else", SHA_V1)


async def test_a_new_version_replaces_the_chunks_instead_of_adding_to_them(
    paper_store: PaperStore, connection: AsyncConnection
) -> None:
    await paper_store.replace(PAPER, CHUNKS, LABELS)
    revised = Paper(PAPER.citekey, PAPER.title, SHA_V2)
    await paper_store.replace(revised, CHUNKS[:1], LABELS)

    cur = await connection.execute("SELECT count(*) FROM paper")
    assert await cur.fetchone() == (1,)
    cur = await connection.execute("SELECT count(*) FROM chunk")
    assert await cur.fetchone() == (1,)
    assert await paper_store.is_current(PAPER.citekey, SHA_V2)


async def test_full_text_search_matches_word_forms(
    paper_store: PaperStore, connection: AsyncConnection
) -> None:
    await paper_store.replace(PAPER, CHUNKS, LABELS)

    # "velocities" and "velocity" share an English stem; the tsvector is generated by Postgres.
    cur = await connection.execute(
        "SELECT ordinal FROM chunk WHERE tsv @@ plainto_tsquery('english', %s)",
        ("longitudinal velocities",),
    )
    assert await cur.fetchall() == [(1,)]


@pytest.mark.skipif(not LIANG_PDF.exists(), reason="sample PDF not in tests/fixtures/private/")
async def test_ingesting_the_same_pdf_twice_embeds_it_once(paper_store: PaperStore) -> None:
    first = await ingest_pdf(LIANG_PDF, "liang2021yaw", PAPER.title, paper_store)
    second = await ingest_pdf(LIANG_PDF, "liang2021yaw", PAPER.title, paper_store)

    assert (first, second) == (Outcome.STORED, Outcome.UNCHANGED)
